name: Control-Center
version: '${project.version}'
main: dev.expx.ctrlctr.center.Ctrlctr
api-version: '1.21'
bootstrapper: dev.expx.ctrlctr.center.servertype.papermc.Bootstrapper

dependencies:
  server:
    Vault:
      join-classpath: true
      required: true
    PlaceholderAPI:
      join-classpath: true
      load: BEFORE
      required: true
    Skript:
        join-classpath: true
        load: BEFORE
        required: false